In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/101-simple-linear-regressioncsv/1.01. Simple linear regression.csv


In [2]:
df = pd.read_csv('/kaggle/input/101-simple-linear-regressioncsv/1.01. Simple linear regression.csv')

In [3]:
df.head()

SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83

In [4]:
X = df.iloc[:,0].values
y = df.iloc[:,1].values

In [5]:
X

array([1714, 1664, 1760, 1685, 1693, 1670, 1764, 1764, 1792, 1850, 1735,
       1775, 1735, 1712, 1773, 1872, 1755, 1674, 1842, 1786, 1761, 1722,
       1663, 1687, 1974, 1826, 1787, 1821, 2020, 1794, 1769, 1934, 1775,
       1855, 1880, 1849, 1808, 1954, 1777, 1831, 1865, 1850, 1966, 1702,
       1990, 1925, 1824, 1956, 1857, 1979, 1802, 1855, 1907, 1634, 1879,
       1887, 1730, 1953, 1781, 1891, 1964, 1808, 1893, 2041, 1893, 1832,
       1850, 1934, 1861, 1931, 1933, 1778, 1975, 1934, 2021, 2015, 1997,
       2020, 1843, 1936, 1810, 1987, 1962, 2050])

In [6]:
y

array([2.4 , 2.52, 2.54, 2.74, 2.83, 2.91, 3.  , 3.  , 3.01, 3.01, 3.02,
       3.07, 3.08, 3.08, 3.12, 3.17, 3.17, 3.17, 3.17, 3.19, 3.19, 3.19,
       3.2 , 3.21, 3.24, 3.28, 3.28, 3.28, 3.28, 3.28, 3.28, 3.28, 3.29,
       3.29, 3.29, 3.31, 3.32, 3.34, 3.37, 3.37, 3.37, 3.38, 3.38, 3.39,
       3.39, 3.4 , 3.4 , 3.4 , 3.41, 3.41, 3.41, 3.42, 3.42, 3.42, 3.44,
       3.47, 3.47, 3.47, 3.47, 3.48, 3.49, 3.49, 3.5 , 3.51, 3.51, 3.52,
       3.52, 3.54, 3.58, 3.58, 3.59, 3.59, 3.6 , 3.6 , 3.61, 3.62, 3.64,
       3.65, 3.71, 3.71, 3.71, 3.73, 3.76, 3.81])

In [7]:
def fit(X_train, Y_train):
    num = 0
    den = 0
    m = 0
    b = 0
    for i in range(X_train.shape[0]):
      num = num + (Y_train[i] - Y_train.mean()) * (X_train[i] - X_train.mean())
      den = den + (X_train[i] - X_train.mean()) * (X_train[i] - X_train.mean())
        
    m = num/den
    b = Y_train.mean() - (m * X_train.mean())
        
    return m,b
        
def predict(X_test):
  return m * x_test + b

In [8]:
from sklearn.model_selection import train_test_split
X_train, x_test, Y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

In [9]:
X_train.shape

(67,)

In [10]:
x_test.shape

(17,)

In [11]:
m,b = fit(X_train, Y_train)
print(m,b)

0.0016306191481003421 0.3318195666158803


In [12]:
print(predict(x_test[0]))

[3.31911385 3.37292428 3.44141028 3.20333989 3.21638484 3.39575295
 3.41858161 3.16094379 3.22616855 3.06147602 3.22616855 3.38433861
 3.35661809 3.20170927 3.33542004 3.12343955 3.65991325]


In [13]:
y_test

array([3.52, 3.37, 3.42, 3.19, 3.28, 3.44, 3.5 , 3.08, 3.29, 3.17, 3.07,
       3.17, 3.42, 2.54, 3.17, 3.08, 3.51])

In [14]:
X = df[['SAT']]
y = df['GPA']

from sklearn.model_selection import train_test_split
X_train, x_test, Y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

In [15]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, Y_train)

m1 = model.coef_
b1 = model.intercept_
print(m1,b1)

[0.00163062] 0.3318195666158803
